# -*- coding: utf-8 -*-
"""koordinat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IAbD_UKImMoyZrQwwqhI7LQNul-SF3w9
"""

import streamlit as st
import math

def hitung_jarak(t1, t2):
    """Menghitung jarak antara dua titik dalam koordinat Kartesius"""
    return math.sqrt((t2[0] - t1[0])**2 + (t2[1] - t1[1])**2)

def hitung_gradien(t1, t2):
    """Menghitung gradien garis yang menghubungkan dua titik"""
    try:
        return (t2[1] - t1[1]) / (t2[0] - t1[0])
    except ZeroDivisionError:
        return None  # Gradien tidak terdefinisi untuk garis vertikal

# Konfigurasi tampilan aplikasi
st.set_page_config(page_title="Kalkulator Koordinat Kartesius", layout="centered")
st.title("📍 Kalkulator Koordinat Kartesius")
st.write("Masukkan koordinat dua titik untuk mengetahui jarak dan kemiringan garis di antaranya.")

# Form input interaktif
with st.form("form_input"):
    col1, col2 = st.columns(2)
    with col1:
        x1 = st.number_input("Titik Pertama - X1", value=0.0, format="%.2f")
        y1 = st.number_input("Titik Pertama - Y1", value=0.0, format="%.2f")
    with col2:
        x2 = st.number_input("Titik Kedua - X2", value=0.0, format="%.2f")
        y2 = st.number_input("Titik Kedua - Y2", value=0.0, format="%.2f")

    submit = st.form_submit_button("🔍 Hitung")

# Logika perhitungan saat tombol ditekan
if submit:
    titik1 = (x1, y1)
    titik2 = (x2, y2)

    if titik1 == titik2:
        st.error("❗ Titik pertama dan kedua tidak boleh sama.")
    else:
        jarak = hitung_jarak(titik1, titik2)
        gradien = hitung_gradien(titik1, titik2)

        st.markdown("### 🔎 Hasil Perhitungan")
        st.success(f"📏 Jarak antara titik {titik1} dan {titik2} adalah **{jarak:.2f} satuan**.")

        if gradien is None:
            st.warning("📈 Gradien garis: *Tidak terdefinisi* (garis vertikal)")
        else:
            st.info(f"📈 Gradien garis: **{gradien:.2f}**")